version: '3'

services:
  db:
    image: postgres
    volumes:
      - web_template:/var/lib/postgresql/data/
    env_file:
      - ./services/database/.env
    ports:
      - 5432:5432 

  web-template:
    build:
      context: services/app
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    expose:  # new
      - 5000
    env_file:
      - ./services/app/.env
    depends_on:
      - db
      - redis
    labels:  # new
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`flask.localhost`)"

  celery-worker:
    build:
      context: services/app
      dockerfile: Dockerfile
    command: celery --app manage.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - ./services/app/.env
    depends_on:
      - web-template
      - redis

  redis:
    image: redis:6-alpine

  traefik:  # new
    image: traefik:v2.2
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - "./services/traefik1/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  web_template:
